In [18]:
from sklearn.utils import shuffle

df = pd.read_csv("postings.csv")
df = shuffle(df)
data = df[:600]
data

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
56821,3901941311,VinFast US,Internal Control Specialist,"JOB SUMMARY:Reporting to the Director, Interna...",120000.00,YEARLY,"Los Angeles, CA",74710480.0,2.0,NaN,...,NaN,1.713468e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,105000.0,90001.0,6037.0
120236,3906228709,Sunglass Hut,Sales Associate Sunglass Hut,Requisition ID: 843252\n\nStore #: 003543 Sung...,NaN,NaN,"Palm Desert, CA",3642491.0,3.0,NaN,...,NaN,1.713563e+12,careers.essilorluxottica.com,0,PART_TIME,NaN,NaN,NaN,92211.0,NaN
116415,3905868666,"Millennium Recruiting, Inc.",Fundraising Associate,Rose Gold Marketing helps you achieve your goa...,NaN,NaN,"Dallas, TX",10425374.0,2.0,NaN,...,NaN,1.713538e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,75201.0,48113.0
69299,3902806222,Capgemini,Javascript Developer- React,Job Title: Lead React Employee Type: Full-Time...,NaN,NaN,"Charlotte, NC",157240.0,22.0,NaN,...,NaN,1.713550e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,28202.0,37119.0
46742,3900978159,Ultimate Staffing,Front Office Coordinator,Seeking a outgoing and friendly Front Office C...,20.00,HOURLY,"Sacramento, CA",7260.0,11.0,NaN,...,NaN,1.713395e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,41600.0,95811.0,6067.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104453,3905298847,Bose Corporation,Ecommerce Merchandiser,You know the moment. It’s the first notes of t...,NaN,NaN,"Framingham, MA",4030.0,8.0,NaN,...,NaN,1.713476e+12,boseallaboutme.wd1.myworkdayjobs.com,0,FULL_TIME,NaN,NaN,NaN,1701.0,25017.0
123818,3906264345,"TalentBurst, an Inc 5000 company",Quality Engineer,Position: Quality Engineer I/IILocation: Irvin...,50.00,HOURLY,"Irvine, CA",122451.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,CONTRACT,USD,BASE_SALARY,93600.0,92602.0,NaN
14307,3887867856,Southland Industries,Human Resources Business Partner,Job Description\n\nPEOPLE FIRST: BUILDING TALE...,NaN,NaN,"Dulles Town Center, VA",22132.0,10.0,NaN,...,NaN,1.712370e+12,southland.silkroad.com,0,FULL_TIME,NaN,NaN,NaN,20189.0,NaN
245,3706460061,Sharper Office Admin,Admininistrative Assistant Intern,Company Description\nSharper Office Admin prov...,NaN,NaN,New York City Metropolitan Area,77897822.0,25.0,NaN,...,NaN,1.713393e+12,NaN,0,INTERNSHIP,NaN,NaN,NaN,NaN,NaN
42480,3899535580,Molina Healthcare,"Case Manager, LTSS (RN) - Field Travel in Rock...",Job Description\n\nFamily Care with My Choice ...,51.49,HOURLY,"Janesville, WI",15283.0,7.0,NaN,...,NaN,1.713281e+12,careers.molinahealthcare.com,0,FULL_TIME,USD,BASE_SALARY,78260.0,53545.0,55105.0

In [19]:
del data['job_id']
del data['company_name']
del data['company_id']
del data['views']
del data['posting_domain']
del data['sponsored']
del data['zip_code']
del data['fips']
del data['listed_time']
del data['original_listed_time']

data

,title,description,max_salary,pay_period,location,med_salary,min_salary,formatted_work_type,applies,remote_allowed,...,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,work_type,currency,compensation_type,normalized_salary
56821,Internal Control Specialist,"JOB SUMMARY:Reporting to the Director, Interna...",120000.00,YEARLY,"Los Angeles, CA",NaN,90000.00,Full-time,NaN,NaN,...,NaN,ComplexOnsiteApply,1.716060e+12,NaN,Associate,NaN,FULL_TIME,USD,BASE_SALARY,105000.0
120236,Sales Associate Sunglass Hut,Requisition ID: 843252\n\nStore #: 003543 Sung...,NaN,NaN,"Palm Desert, CA",NaN,NaN,Part-time,NaN,NaN,...,https://careers.essilorluxottica.com/job/Palm-...,OffsiteApply,1.716155e+12,NaN,Entry level,NaN,PART_TIME,NaN,NaN,NaN
116415,Fundraising Associate,Rose Gold Marketing helps you achieve your goa...,NaN,NaN,"Dallas, TX",NaN,NaN,Full-time,NaN,NaN,...,NaN,ComplexOnsiteApply,1.716130e+12,NaN,Entry level,NaN,FULL_TIME,NaN,NaN,NaN
69299,Javascript Developer- React,Job Title: Lead React Employee Type: Full-Time...,NaN,NaN,"Charlotte, NC",NaN,NaN,Full-time,10.0,NaN,...,NaN,ComplexOnsiteApply,1.716142e+12,NaN,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,NaN
46742,Front Office Coordinator,Seeking a outgoing and friendly Front Office C...,20.00,HOURLY,"Sacramento, CA",NaN,20.00,Full-time,4.0,NaN,...,NaN,SimpleOnsiteApply,1.715987e+12,NaN,Entry level,NaN,FULL_TIME,USD,BASE_SALARY,41600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104453,Ecommerce Merchandiser,You know the moment. It’s the first notes of t...,NaN,NaN,"Framingham, MA",NaN,NaN,Full-time,NaN,NaN,...,https://boseallaboutme.wd1.myworkdayjobs.com/B...,OffsiteApply,1.716068e+12,NaN,Entry level,NaN,FULL_TIME,NaN,NaN,NaN
123818,Quality Engineer,Position: Quality Engineer I/IILocation: Irvin...,50.00,HOURLY,"Irvine, CA",NaN,40.00,Contract,NaN,NaN,...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,CONTRACT,USD,BASE_SALARY,93600.0
14307,Human Resources Business Partner,Job Description\n\nPEOPLE FIRST: BUILDING TALE...,NaN,NaN,"Dulles Town Center, VA",NaN,NaN,Full-time,NaN,NaN,...,https://southland.silkroad.com/epostings/index...,OffsiteApply,1.714962e+12,NaN,Mid-Senior level,NaN,FULL_TIME,NaN,NaN,NaN
245,Admininistrative Assistant Intern,Company Description\nSharper Office Admin prov...,NaN,NaN,New York City Metropolitan Area,NaN,NaN,Internship,7.0,1.0,...,NaN,ComplexOnsiteApply,1.715985e+12,NaN,NaN,NaN,INTERNSHIP,NaN,NaN,NaN
42480,"Case Manager, LTSS (RN) - Field Travel in Rock...",Job Description\n\nFamily Care with My Choice ...,51.49,HOURLY,"Janesville, WI",NaN,23.76,Full-time,NaN,1.0,...,https://ad.doubleclick.net/ddm/clk/517598247;3...,OffsiteApply,1.715873e+12,NaN,Mid-Senior level,NaN,FULL_TIME,USD,BASE_SALARY,78260.0

In [20]:
data.to_csv('600_jobs.csv')